version: '3.8'

services:
  app:
    build: .
    ports:
      - '3000'
    environment:
      - PORT=3000
      - MONGO_CONNECTING_USUARIOS=${MONGO_CONNECTING_USUARIOS}
      - MONGO_CONNECTING_FUNCIONARIOS=${MONGO_CONNECTING_FUNCIONARIOS}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - .:/app
    networks:
      - app-network
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: '0.5'
          memory: '512M'

  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '256M'

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '8080:80' # A porta 80 do Nginx será exposta
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
