name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Aciona o pipeline para commits na branch principal

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379:6379

      mongo:
        image: mongo:latest
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: ${{ secrets.MONGO_DB_USERNAME }}
          MONGO_INITDB_ROOT_PASSWORD: ${{ secrets.MONGO_DB_PASSWORD }}

    steps:
    - name: Checar código
      uses: actions/checkout@v2

    - name: Configurar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Instalar dependências
      run: npm install

    - name: Esperar MongoDB estar pronto
      run: |
        until nc -z localhost 27017; do
          echo "Aguardando MongoDB iniciar..."
          sleep 2
        done
      shell: bash

    - name: Definir variáveis de ambiente
      run: |
        echo "MONGO_CONNECTING_FUNCIONARIOS=mongodb://${{ secrets.MONGO_DB_USERNAME }}:${{ secrets.MONGO_DB_PASSWORD }}@localhost:27017/Funcionarios" >> $GITHUB_ENV
        echo "MONGO_CONNECTING_USUARIOS=mongodb://${{ secrets.MONGO_DB_USERNAME }}:${{ secrets.MONGO_DB_PASSWORD }}@localhost:27017/usuarios" >> $GITHUB_ENV
        echo "REDIS_URL=redis://127.0.0.1:6379" >> $GITHUB_ENV

    - name: Rodar os testes
      run: npm test

    - name: Rodar linting
      run: npm run lint

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Só roda após o job de build ter sido concluído com sucesso

    steps:
    - name: Checar código
      uses: actions/checkout@v2

    - name: Deploy para o OnRender
      env:
        RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
      run: |
        curl -X POST \
          -H "Authorization: Bearer $RENDER_API_KEY" \
          -d '{"branch": "main"}' \
          https://api.onrender.com/v1/services/srv-cu73jaq3esus73ffmn4g/deploy
