name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Aciona o pipeline para commits na branch principal

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
    - name: Checar código
      uses: actions/checkout@v2

    - name: Configurar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Instalar dependências
      run: npm install

    - name: Check environment variables
      run: echo "MONGO_CONNECTING_FUNCIONARIOS is set"
      env:
        MONGO_CONNECTING_FUNCIONARIOS: ${{ secrets.MONGO_CONNECTING_FUNCIONARIOS }} >> $GITHUB_ENV
    

    - name: Definir variáveis de ambiente
      run: echo "REDIS_URL=redis://127.0.0.1:6379" >> $GITHUB_ENV

    - name: Rodar os testes
      run: npm test

    - name: Rodar linting
      run: npm run lint

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Só roda após o job de build ter sido concluído com sucesso

    steps:
    - name: Checar código
      uses: actions/checkout@v2


    - name: Deploy para o OnRender
      env:
        RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}  # Chave API do OnRender
      run: |
        curl -X POST \
          -H "Authorization: Bearer $RENDER_API_KEY" \
          -d '{"branch": "main"}' \
          https://api.onrender.com/v1/services/srv-cu73jaq3esus73ffmn4g/deploy
